version: '3.3'

services:
  frontend:
    build: .
    ports:
      - "8080:80"
    volumes:
      # 启用热更新，挂载本地目录
      - .:/usr/share/nginx/html
    restart: unless-stopped
    environment:
      - NODE_ENV=production